name: NestJS Backend CI

on:
  push:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        working-directory: Backend/lms
          
      - name: Lint
        run: npm run lint
        working-directory: Backend/lms
          
      - name: Run Tests
        run: npm run test
        working-directory: Backend/lms
          
      - name: Build
        run: npm run build
        working-directory: Backend/lms
