name: NestJS Backend CI

on:
  push:
    paths:
      - 'Backend/lms/my-nestjs-project/**'
      - '.github/workflows/backend.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'Backend/lms/my-nestjs-project'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Verify files
        run: |
          ls -la
          ls -la Backend/lms/my-nestjs-project
        working-directory: .

      - name: Install dependencies
        run: npm ci
        working-directory: Backend/lms/my-nestjs-project

      - name: Lint
        run: npm run lint
        working-directory: Backend/lms/my-nestjs-project

      - name: Run Tests
        run: npm run test
        working-directory: Backend/lms/my-nestjs-project

      - name: Build
        run: npm run build
        working-directory: Backend/lms/my-nestjs-project
