name: CI/CD Pipeline for Flutter, NestJS, and PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ---------- FLUTTER CI/CD ----------
  flutter:
    name: Build & Test Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"

      - name: Install Dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Run Flutter Tests
        run: flutter test
        working-directory: frontend

      - name: Build APK
        run: flutter build apk --release
        working-directory: frontend

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk

  # ---------- NESTJS CI/CD ----------
  backend:
    name: Build & Test NestJS
    runs-on: ubuntu-latest
    needs: flutter  # Runs after Flutter job

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Lint Code
        run: npm run lint
        working-directory: backend

      - name: Run Tests
        run: npm run test
        working-directory: backend

      - name: Build Project
        run: npm run build
        working-directory: backend

  # ---------- DEPLOYMENT ----------
  deploy:
    name: Deploy Backend & Flutter
    runs-on: ubuntu-latest
    needs: backend  # Runs after NestJS job
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart all

            cd /var/www/frontend
            git pull origin main
            flutter build apk --release
