name: Flutter Frontend CI
on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'
jobs:
  build:
    name: Build & Test Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Verify Directory Structure & Flutter Project
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Frontend directory content:"
          ls -la frontend/ || echo "frontend directory not found"
          echo "Looking for pubspec.yaml:"
          find frontend/ -name "pubspec.yaml" || echo "pubspec.yaml not found"
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          cache: true
          
      - name: Verify Flutter Installation
        run: flutter doctor -v
        
      - name: Install Dependencies
        run: |
          cd frontend
          flutter pub get --verbose
        
      - name: Build APK with detailed logs
        run: |
          cd frontend
          flutter build apk --release --verbose
