name: Flutter Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    name: Build & Test Flutter
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Run tests
        run: flutter test
        working-directory: frontend

      - name: Build APK
        run: flutter build apk --release
        working-directory: frontend

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
