name: Flutter Frontend CI

on:
  push:
    paths:
      - 'frontend/lms/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/lms/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    name: Build & Test Flutter
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          cache: true

      - name: Verify Flutter Installation
        run: flutter doctor

      - name: Install Dependencies
        run: flutter pub get
        working-directory: frontend/lms

      - name: Run Tests
        run: flutter test
        working-directory: frontend/lms

      - name: Build APK
        run: flutter build apk --release
        working-directory: frontend/lms

      - name: Verify APK Exists
        run: ls -lh frontend/lms/build/app/outputs/flutter-apk/
      
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: flutter-apk
          path: frontend/lms/build/app/outputs/flutter-apk/**/*.apk

      - name: Cleanup Artifacts
        if: always()
        run: rm -rf frontend/lms/build
